---
root: true
parser: "babel-eslint"
extends:
  - "airbnb"
  - plugin:import/errors
plugins:
  - no-not-accumulator-reassign
env:
    browser: true
    node: true
    mocha: true
rules:
  space-before-function-paren: [1, "never"]
  object-curly-spacing: [2, "never"]
  no-return-assign: 0
  react/jsx-first-prop-new-line: 0
  no-underscore-dangle: 0
  import/namespace: 1
  import/imports-first: 0
  import/no-extraneous-dependencies: 0
  import/newline-after-import: 0
  # no-unused-vars: 0
  import/no-duplicates: 2
  react/jsx-key: 2
  react/prefer-es6-class: 0
  react/jsx-closing-bracket-location: [2, "after-props"]
  react/no-multi-comp: 1
  react/jsx-no-bind: 1
  react/prefer-stateless-function: 1
  react/jsx-filename-extension: 0
  prefer-arrow-callback: 0
  no-mixed-spaces-and-tabs: 0
  new-cap: 0
  max-len: [2, 80, 2, {ignoreComments: true}]
  consistent-return: 0
  func-names: 0

  react/sort-comp: 0
  no-param-reassign: 0
  prefer-template: 0
  arrow-body-style: 0
  # indent: [0, 'tab', { 'SwitchCase': 0, 'VariableDeclarator': 1 }]
  no-use-before-define: 0
  no-confusing-arrow: 0
  global-require: 0
  no-not-accumulator-reassign/no-not-accumulator-reassign: [2, ['reduce'], {props: true}]
